/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.ui.contentassist;

import org.xtext.projectparamorel.dsl.ui.contentassist.AbstractDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
