/*
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/projectparamorel/dsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
