/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl;

import org.xtext.projectparamorel.dsl.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
