/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.projectparamorel.dsl.ui.AbstractDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
}
