/*
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.projectparamorel.dsl.dsl.Entry

@ExtendWith(InjectionExtension)
@InjectWith(DslInjectorProvider)
class DslParsingTest {
	@Inject
	ParseHelper<Entry> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			I want my preferences to reward shorterSequencesOfActions by a weight of 5.
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
