/*
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.projectparamorel.dsl.ui.internal.DslActivator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.projectparamorel.dsl.Dsl");
	}

}
