/*
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
