/*
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PreferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.projectparamorel.dsl.Dsl.Preference");
		private final Assignment cScoresAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScoresScoreParserRuleCall_0 = (RuleCall)cScoresAssignment.eContents().get(0);
		
		//Preference:
		//	scores+=Score*;
		@Override public ParserRule getRule() { return rule; }
		
		//scores+=Score*
		public Assignment getScoresAssignment() { return cScoresAssignment; }
		
		//Score
		public RuleCall getScoresScoreParserRuleCall_0() { return cScoresScoreParserRuleCall_0; }
	}
	public class ScoreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.projectparamorel.dsl.Dsl.Score");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCategoryAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCategoryStateOptionParserRuleCall_0_0 = (RuleCall)cCategoryAssignment_0.eContents().get(0);
		private final Assignment cFeatureAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFeatureQualifiedNameParserRuleCall_1_0 = (RuleCall)cFeatureAssignment_1.eContents().get(0);
		private final Keyword cByKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWeightKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueINTTerminalRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cFullStopKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Score:
		//	category=StateOption feature=QualifiedName 'by' 'weight' value=INT '.';
		@Override public ParserRule getRule() { return rule; }
		
		//category=StateOption feature=QualifiedName 'by' 'weight' value=INT '.'
		public Group getGroup() { return cGroup; }
		
		//category=StateOption
		public Assignment getCategoryAssignment_0() { return cCategoryAssignment_0; }
		
		//StateOption
		public RuleCall getCategoryStateOptionParserRuleCall_0_0() { return cCategoryStateOptionParserRuleCall_0_0; }
		
		//feature=QualifiedName
		public Assignment getFeatureAssignment_1() { return cFeatureAssignment_1; }
		
		//QualifiedName
		public RuleCall getFeatureQualifiedNameParserRuleCall_1_0() { return cFeatureQualifiedNameParserRuleCall_1_0; }
		
		//'by'
		public Keyword getByKeyword_2() { return cByKeyword_2; }
		
		//'weight'
		public Keyword getWeightKeyword_3() { return cWeightKeyword_3; }
		
		//value=INT
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_4_0() { return cValueINTTerminalRuleCall_4_0; }
		
		//'.'
		public Keyword getFullStopKeyword_5() { return cFullStopKeyword_5; }
	}
	public class StateOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.projectparamorel.dsl.Dsl.StateOption");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cRewardKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cPunishKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//StateOption:
		//	'Reward' | 'Punish';
		@Override public ParserRule getRule() { return rule; }
		
		//'Reward' | 'Punish'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Reward'
		public Keyword getRewardKeyword_0() { return cRewardKeyword_0; }
		
		//'Punish'
		public Keyword getPunishKeyword_1() { return cPunishKeyword_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.projectparamorel.dsl.Dsl.QualifiedName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cDeletionKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cShorterSequencesOfActionsKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cLongerSequencesOfActionsKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cRepairingLowerInTheContextHierarchiesKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cRepairingHigherInTheContextHierarchiesKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cModificationOfTheOriginalModelKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//QualifiedName:
		//	'deletion' | 'shorterSequencesOfActions' | 'longerSequencesOfActions' | 'repairingLowerInTheContextHierarchies' |
		//	'repairingHigherInTheContextHierarchies' | 'modificationOfTheOriginalModel';
		@Override public ParserRule getRule() { return rule; }
		
		//'deletion' | 'shorterSequencesOfActions' | 'longerSequencesOfActions' | 'repairingLowerInTheContextHierarchies' |
		//'repairingHigherInTheContextHierarchies' | 'modificationOfTheOriginalModel'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'deletion'
		public Keyword getDeletionKeyword_0() { return cDeletionKeyword_0; }
		
		//'shorterSequencesOfActions'
		public Keyword getShorterSequencesOfActionsKeyword_1() { return cShorterSequencesOfActionsKeyword_1; }
		
		//'longerSequencesOfActions'
		public Keyword getLongerSequencesOfActionsKeyword_2() { return cLongerSequencesOfActionsKeyword_2; }
		
		//'repairingLowerInTheContextHierarchies'
		public Keyword getRepairingLowerInTheContextHierarchiesKeyword_3() { return cRepairingLowerInTheContextHierarchiesKeyword_3; }
		
		//'repairingHigherInTheContextHierarchies'
		public Keyword getRepairingHigherInTheContextHierarchiesKeyword_4() { return cRepairingHigherInTheContextHierarchiesKeyword_4; }
		
		//'modificationOfTheOriginalModel'
		public Keyword getModificationOfTheOriginalModelKeyword_5() { return cModificationOfTheOriginalModelKeyword_5; }
	}
	
	
	private final PreferenceElements pPreference;
	private final ScoreElements pScore;
	private final StateOptionElements pStateOption;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPreference = new PreferenceElements();
		this.pScore = new ScoreElements();
		this.pStateOption = new StateOptionElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.projectparamorel.dsl.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Preference:
	//	scores+=Score*;
	public PreferenceElements getPreferenceAccess() {
		return pPreference;
	}
	
	public ParserRule getPreferenceRule() {
		return getPreferenceAccess().getRule();
	}
	
	//Score:
	//	category=StateOption feature=QualifiedName 'by' 'weight' value=INT '.';
	public ScoreElements getScoreAccess() {
		return pScore;
	}
	
	public ParserRule getScoreRule() {
		return getScoreAccess().getRule();
	}
	
	//StateOption:
	//	'Reward' | 'Punish';
	public StateOptionElements getStateOptionAccess() {
		return pStateOption;
	}
	
	public ParserRule getStateOptionRule() {
		return getStateOptionAccess().getRule();
	}
	
	//QualifiedName:
	//	'deletion' | 'shorterSequencesOfActions' | 'longerSequencesOfActions' | 'repairingLowerInTheContextHierarchies' |
	//	'repairingHigherInTheContextHierarchies' | 'modificationOfTheOriginalModel';
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
