/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.projectparamorel.dsl.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/projectparamorel/dsl/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.ExperienceImpl <em>Experience</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projectparamorel.dsl.dsl.impl.ExperienceImpl
   * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getExperience()
   * @generated
   */
  int EXPERIENCE = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__ENTRIES = 0;

  /**
   * The number of structural features of the '<em>Experience</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projectparamorel.dsl.dsl.impl.EntryImpl
   * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 1;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.MetricImpl <em>Metric</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projectparamorel.dsl.dsl.impl.MetricImpl
   * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getMetric()
   * @generated
   */
  int METRIC = 2;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__STATE = ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__NAME = ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__WEIGHT = ENTRY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Metric</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.xtext.projectparamorel.dsl.dsl.Experience <em>Experience</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Experience</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Experience
   * @generated
   */
  EClass getExperience();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projectparamorel.dsl.dsl.Experience#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Experience#getEntries()
   * @see #getExperience()
   * @generated
   */
  EReference getExperience_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.projectparamorel.dsl.dsl.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for class '{@link org.xtext.projectparamorel.dsl.dsl.Metric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Metric
   * @generated
   */
  EClass getMetric();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Metric#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Metric#getState()
   * @see #getMetric()
   * @generated
   */
  EAttribute getMetric_State();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Metric#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Metric#getName()
   * @see #getMetric()
   * @generated
   */
  EAttribute getMetric_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Metric#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Metric#getWeight()
   * @see #getMetric()
   * @generated
   */
  EAttribute getMetric_Weight();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.ExperienceImpl <em>Experience</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projectparamorel.dsl.dsl.impl.ExperienceImpl
     * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getExperience()
     * @generated
     */
    EClass EXPERIENCE = eINSTANCE.getExperience();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPERIENCE__ENTRIES = eINSTANCE.getExperience_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projectparamorel.dsl.dsl.impl.EntryImpl
     * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.MetricImpl <em>Metric</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projectparamorel.dsl.dsl.impl.MetricImpl
     * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getMetric()
     * @generated
     */
    EClass METRIC = eINSTANCE.getMetric();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC__STATE = eINSTANCE.getMetric_State();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC__NAME = eINSTANCE.getMetric_Name();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC__WEIGHT = eINSTANCE.getMetric_Weight();

  }

} //DslPackage
