/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.projectparamorel.dsl.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/projectparamorel/dsl/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.PreferenceImpl <em>Preference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projectparamorel.dsl.dsl.impl.PreferenceImpl
   * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getPreference()
   * @generated
   */
  int PREFERENCE = 0;

  /**
   * The feature id for the '<em><b>Scores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE__SCORES = 0;

  /**
   * The number of structural features of the '<em>Preference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.ScoreImpl <em>Score</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projectparamorel.dsl.dsl.impl.ScoreImpl
   * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getScore()
   * @generated
   */
  int SCORE = 1;

  /**
   * The feature id for the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE__CATEGORY = 0;

  /**
   * The feature id for the '<em><b>Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE__FEATURE = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE__VALUE = 2;

  /**
   * The number of structural features of the '<em>Score</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.projectparamorel.dsl.dsl.Preference <em>Preference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preference</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Preference
   * @generated
   */
  EClass getPreference();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projectparamorel.dsl.dsl.Preference#getScores <em>Scores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scores</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Preference#getScores()
   * @see #getPreference()
   * @generated
   */
  EReference getPreference_Scores();

  /**
   * Returns the meta object for class '{@link org.xtext.projectparamorel.dsl.dsl.Score <em>Score</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Score</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Score
   * @generated
   */
  EClass getScore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Score#getCategory <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Category</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Score#getCategory()
   * @see #getScore()
   * @generated
   */
  EAttribute getScore_Category();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Score#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Feature</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Score#getFeature()
   * @see #getScore()
   * @generated
   */
  EAttribute getScore_Feature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projectparamorel.dsl.dsl.Score#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.projectparamorel.dsl.dsl.Score#getValue()
   * @see #getScore()
   * @generated
   */
  EAttribute getScore_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.PreferenceImpl <em>Preference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projectparamorel.dsl.dsl.impl.PreferenceImpl
     * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getPreference()
     * @generated
     */
    EClass PREFERENCE = eINSTANCE.getPreference();

    /**
     * The meta object literal for the '<em><b>Scores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREFERENCE__SCORES = eINSTANCE.getPreference_Scores();

    /**
     * The meta object literal for the '{@link org.xtext.projectparamorel.dsl.dsl.impl.ScoreImpl <em>Score</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projectparamorel.dsl.dsl.impl.ScoreImpl
     * @see org.xtext.projectparamorel.dsl.dsl.impl.DslPackageImpl#getScore()
     * @generated
     */
    EClass SCORE = eINSTANCE.getScore();

    /**
     * The meta object literal for the '<em><b>Category</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCORE__CATEGORY = eINSTANCE.getScore_Category();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCORE__FEATURE = eINSTANCE.getScore_Feature();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCORE__VALUE = eINSTANCE.getScore_Value();

  }

} //DslPackage
