/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.projectparamorel.dsl.dsl.DslPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
} // Entry
