/**
 * generated by Xtext 2.16.0
 */
package org.xtext.projectparamorel.dsl.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Experience</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projectparamorel.dsl.dsl.Experience#getEntries <em>Entries</em>}</li>
 * </ul>
 *
 * @see org.xtext.projectparamorel.dsl.dsl.DslPackage#getExperience()
 * @model
 * @generated
 */
public interface Experience extends EObject
{
  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.projectparamorel.dsl.dsl.Entry}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entries</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see org.xtext.projectparamorel.dsl.dsl.DslPackage#getExperience_Entries()
   * @model containment="true"
   * @generated
   */
  EList<Entry> getEntries();

} // Experience
